name: UndereducateGUI
version: ${project.version}
main: site.undereducate.UndereducateGUIPlugin
api-version: 1.16
authors: [Undereducate]
description: UndereducateGUI is a feature filled plugin to view everyone online in a GUI
